/** TanStack Query keys. Everything valued starts with "portfolio", so one invalidation refreshes it all. */
export const keys = {
  accounts: ["accounts"] as const,
  instruments: ["instruments"] as const,
  accountUsage: (id: number) => ["accounts", "usage", id] as const,
  portfolio: ["portfolio"] as const,
  summary: (ids: readonly number[]) => ["portfolio", "summary", ids] as const,
  history: (ids: readonly number[], from: string | null) => ["portfolio", "history", ids, from] as const,
  exposure: (ids: readonly number[], day: string) => ["portfolio", "exposure", ids, day] as const,
  exposureHistory: (ids: readonly number[], from: string | null) => ["portfolio", "exposure-history", ids, from] as const,
  closed: (ids: readonly number[]) => ["portfolio", "closed", ids] as const,
  limits: ["portfolio", "limits"] as const,
  analytics: (ids: readonly number[], period: string) => ["portfolio", "analytics", ids, period] as const,
  holdings: (ids: readonly number[], period: string) => ["portfolio", "holdings", ids, period] as const,
  tagAnalytics: (ids: readonly number[], period: string) => ["portfolio", "tag-analytics", ids, period] as const,
  income: (ids: readonly number[], period: string) => ["portfolio", "income", ids, period] as const,
  positions: (ids: readonly number[]) => ["portfolio", "positions", ids] as const,
  position: (accountId: number, instrumentId: number) => ["portfolio", "position", accountId, instrumentId] as const,
  positionPrices: (accountId: number, instrumentId: number, from: string | null) =>
    ["portfolio", "position-prices", accountId, instrumentId, from] as const,
  bond: (id: number) => ["portfolio", "bond", id] as const,
  savings: (accountId: number) => ["portfolio", "savings", accountId] as const,
  entries: (filters: object) => ["portfolio", "entries", filters] as const,
  catalog: ["catalog"] as const,
  reviews: ["reviews"] as const,
  review: (id: number) => ["reviews", id] as const,
  tags: ["portfolio", "tags"] as const,
  journal: (target: string) => ["portfolio", "journal", target] as const,
  journalTargets: ["portfolio", "journal-targets"] as const,
  scenarios: ["scenarios"] as const,
  scenario: (id: number) => ["scenarios", id] as const,
  scenarioResults: (id: number) => ["portfolio", "scenario-result", id] as const,
  scenarioResult: (id: number, ids: readonly number[], period: string) =>
    ["portfolio", "scenario-result", id, ids, period] as const,
  scenarioPreview: (body: object, ids: readonly number[]) => ["portfolio", "scenario-preview", body, ids] as const,
};
